pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: 103.143.206.48
    username: root
    password: 123312##
    port: 22
    script:
      - mkdir /root/workspace/SpringWebDemo/ 
      - git init
      - git remote add origin https://github.com/huynamvn/SpringWebDemo.git  
      - git pull origin master
      - mvn install
      - rm -rf /opt/tomcat/webapps/springwebdemo*
      - mv /root/workspace/SpringWebDemo/target/springwebdemo.war /opt/tomcat/webapps/
